name: "Netlify Production Pipeline"

on:
  push:
    branches:
      - main

jobs:
  static_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: "run test case"
        run: echo "running test..."
    
      - name: "Pull code"
        uses: actions/checkout@v2
        
      - name: Deploy System
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with: 
          args: deploy --dir=. --prod
